services:
  postgres:
    container_name: postgres-sql-demo
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_assurance
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-assurance:/var/lib/postgresql/data